Corrects tooltips test; Changes 'STORET' references to 'EPA' (Wqp 1671)
NWQMC/WQP_UI pull request #961
Opened 2021-06-07 21:20 UTC by lprivette

- [ ] Make sure all tests run
- [ ] Update the changelog appropriately

Corrects tooltips test; Changes 'STORET' references to 'EPA'
-----------
https://internal.cida.usgs.gov/jira/browse/WQP-1671

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the JIRA ticket
- [ ] Assign someone to review unless the change is trivial

2021-06-08 12:40 UTC, mbucknell requested changes
I don't believe the services have change so we still need to use "STORET" when querying the services and this is what will be in the expected responses. I am very sure I didn't catch everything so you will want to go through this PR and make sure the changes only effect presentation.

2021-06-08 12:40 UTC, mbucknell commented on assets/js/hbTemplates/coverageMapPopup.hbs
> +                <b>EPA EPA discrete samples: </b>{{EPA_DISCRETE_SAMPLE_COUNT}}
Probably just EPA discrete samples

2021-06-08 12:40 UTC, mbucknell commented on assets/test/js/portal_ui/queryServiceSpec.js
> +                '"EPA-ActivityMetric-Count": "232", "Total-ActivityMetric-Count" : "232",' +
Did the services change? I think we are only changing STORET to EPA on the presentation side. So queries won't change and neither will the expected results from the services.

2021-06-08 12:40 UTC, mbucknell commented on server/wqp/portal_ui_blueprint/templates/cache_manager.html
> +            <option value="EPA">EPA</option>
So this is a case where I believe the value won't change but we want the option name to be EPA.

2021-06-08 12:40 UTC, mbucknell commented on server/wqp/portal_ui_blueprint/views.py
> +    provider_list = ['NWIS', 'EPA', 'STEWARDS', 'BIODATA']
I think this needs to be restored.

2021-06-08 12:40 UTC, mbucknell commented on server/wqp/tests/test_utils.py
> +        assert generate_redis_db_number('EPA') == 2
I think this will need to be restored too

2021-06-08 21:34 UTC, lprivette commented
Wow yes this was quite the overlook on my part. Got a little too find and replace happy 😬 

I'm pulling out the tooltip test fix, and will review/revert the need storet references on this branch (`wqp-1671`)

2021-06-24 12:46 UTC, mbucknell commented on assets/test/js/portal_ui/views/downloadFormViewSpec.js
> +                '<input type="checkbox" name="providers" class="datasources usa-checkbox__input" value="S1" checked/>' +
At some point in your development, I would like the inputs to follow USWDS guidelines more closely. Specifically in this case there doesn't appear to be a label. If there isn't a visible label, then aria-label should be used so that screen readers can navigate the page. I don't think it needs to be dealt with write now but as you update the design of the form, we should pay attention to this.

2021-06-24 12:47 UTC, mbucknell approved these changes

2021-06-24 13:08 UTC, lprivette commented on assets/test/js/portal_ui/views/downloadFormViewSpec.js
> +                '<input type="checkbox" name="providers" class="datasources usa-checkbox__input" value="S1" checked/>' +
Got it.

2021-06-24 13:08 UTC, merged